/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef prismarine_CONSTANTS_H
#define prismarine_CONSTANTS_H

#include "prismarine_types.h"

namespace prismarine {

class prismarineConstants {
 public:
  prismarineConstants();

};

extern const prismarineConstants g_prismarine_constants;

} // namespace

#endif
